import { defineElement, type UsaElement, queryAttr } from '../base';
import { arrowIndex } from './shared';
import css from './code-export.css?raw';

/**
 * 8.9 — low-code component export.
 *
 * `exportComponent(el, format)` turns a live, configured element (any
 * `<usa-*>` with its attributes and light-DOM content) into copy-paste code:
 * `'html'` (a no-build page snippet with a CDN module import), `'react'`
 * (JSX + import), `'vue'` (SFC) or `'json'` (a portable description that the
 * 9.0 declarative DSL reads). Runtime parts Motionary added (`data-usa-*`,
 * `role`, `aria-*` it set, generated parts) are left out.
 *
 * `<usa-code-export for="#el" formats="html,react,vue">` shows that code in
 * tabs next to the live component, re-generates it when the element's
 * attributes change, and copies it with one click (`usa:copy` { format }).
 */
export type ExportFormat = 'html' | 'react' | 'vue' | 'json';
export interface ExportedNode {
  tag: string;
  attrs: Record<string, string>;
  children: (ExportedNode | string)[];
}
export interface UsaCodeExportElement extends UsaElement {
  format: ExportFormat;
  readonly code: string;
  copy(): Promise<boolean>;
}

const RUNTIME_ATTR = /^(data-usa-|data-look$|data-tint$|data-paper$|data-booted$|data-drawn$|data-active$|data-held$|data-tilted$|data-zoomed$|data-dragging$|data-picked$|data-live$|data-lit$|aria-(checked|valuetext|valuenow|label|roledescription|hidden)$|role$|tabindex$|style$)/;
const RUNTIME_CLASS = /^usa-/;

/** A clean, portable description of `el` (runtime parts stripped) (8.9). */
export function describeComponent(el: Element): ExportedNode {
  const attrs: Record<string, string> = {};
  for (const a of Array.from(el.attributes)) {
    if (RUNTIME_ATTR.test(a.name)) continue;
    if (a.name === 'class') {
      const c = a.value.split(/\s+/).filter((x) => x && !RUNTIME_CLASS.test(x)).join(' ');
      if (c) attrs.class = c;
      continue;
    }
    attrs[a.name] = a.value;
  }
  const children: (ExportedNode | string)[] = [];
  el.childNodes.forEach((n) => {
    if (n.nodeType === 3) {
      const t = (n.textContent || '').replace(/\s+/g, ' ');
      if (t.trim()) children.push(t.trim());
    } else if (n.nodeType === 1) {
      const e = n as Element;
      const cls = (e.getAttribute('class') || '').split(/\s+/).filter(Boolean);
      // generated by a component: a marked part, or only usa-* classes and runtime attributes (bars, readouts, overlays)
      if (e.hasAttribute('data-usa-part') || (cls.length && cls.every((c) => RUNTIME_CLASS.test(c)) && Array.from(e.attributes).every((a) => a.name === 'class' || RUNTIME_ATTR.test(a.name)))) return;
      children.push(describeComponent(e));
    }
  });
  return { tag: el.localName, attrs, children };
}

const esc = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/"/g, '&quot;');
const VOID = /*#__PURE__*/ new Set(['img', 'br', 'hr', 'input', 'source', 'meta', 'link', 'wbr', 'area', 'col', 'embed', 'track']);
function markup(n: ExportedNode | string, jsx: boolean, ind: string): string {
  if (typeof n === 'string') return ind + (jsx ? n.replace(/[{}<>]/g, (c) => `{'${c}'}`) : esc(n));
  const at = Object.entries(n.attrs)
    .map(([k, v]) => {
      const key = jsx && k === 'class' ? 'className' : jsx && k === 'for' ? 'htmlFor' : k;
      return v === '' ? ` ${key}` : ` ${key}="${esc(v)}"`;
    })
    .join('');
  if (VOID.has(n.tag)) return `${ind}<${n.tag}${at}${jsx ? ' /' : ''}>`;
  if (!n.children.length) return `${ind}<${n.tag}${at}></${n.tag}>`;
  if (n.children.length === 1 && typeof n.children[0] === 'string') return `${ind}<${n.tag}${at}>${markup(n.children[0], jsx, '')}</${n.tag}>`;
  return `${ind}<${n.tag}${at}>\n${n.children.map((c) => markup(c, jsx, ind + '  ')).join('\n')}\n${ind}</${n.tag}>`;
}

/** Copy-paste code for a live element in `format` (8.9). */
export function exportComponent(el: Element, format: ExportFormat = 'html'): string {
  const d = describeComponent(el);
  if (format === 'json') return JSON.stringify({ $schema: 'motionary/component@1', ...d }, null, 2);
  if (format === 'react')
    return `import { useEffect } from 'react';\nimport { defineWidgets } from 'motionary/components/widgets';\n\nexport function Demo() {\n  useEffect(() => defineWidgets(), []);\n  return (\n${markup(d, true, '    ')}\n  );\n}`;
  if (format === 'vue')
    return `<script setup>\nimport { defineWidgets } from 'motionary/components/widgets';\ndefineWidgets();\n</script>\n\n<template>\n${markup(d, false, '  ')}\n</template>`;
  return `${markup(d, false, '')}\n\n<script type="module">\n  import { defineWidgets } from 'https://cdn.jsdelivr.net/npm/motionary/dist/components/widgets.js';\n  defineWidgets();\n</script>`;
}

const FORMATS: ExportFormat[] = ['html', 'react', 'vue', 'json'];
const LABELS: Record<ExportFormat, string> = { html: 'HTML', react: 'React', vue: 'Vue', json: 'JSON' };

export function defineCodeExport(tag = 'usa-code-export'): CustomElementConstructor | undefined {
  return defineElement(
    tag,
    (Base) => {
      class UsaCodeExport extends Base {
        static get observedAttributes(): string[] {
          return ['for', 'formats'];
        }
        private _f: ExportFormat = 'html';
        private _mo: MutationObserver | null = null;
        private fmts(): ExportFormat[] {
          const l = this.str('formats').split(',').map((s) => s.trim()).filter((s): s is ExportFormat => (FORMATS as string[]).includes(s));
          return l.length ? l : ['html', 'react', 'vue'];
        }
        private src(): Element | null {
          const f = this.str('for');
          return f ? queryAttr(f) : this.querySelector(':scope > :not([data-usa-part])');
        }
        get format(): ExportFormat {
          return this._f;
        }
        set format(f: ExportFormat) {
          if (!this.fmts().includes(f)) return;
          const changed = f !== this._f;
          this._f = f;
          this.render();
          const pre = this.querySelector('.usa-ce-code');
          if (changed && pre && !this.reduced) this.motion(pre, [{ opacity: 0.35, transform: 'translateY(4px)' }, { opacity: 1, transform: 'none' }], { duration: 220, easing: 'ease-out' });
        }
        get code(): string {
          const s = this.src();
          return s ? exportComponent(s, this._f) : '';
        }
        mount(): void {
          this.querySelectorAll(':scope > [data-usa-part]').forEach((n) => n.remove());
          const fm = this.fmts();
          if (!fm.includes(this._f)) this._f = fm[0];
          const id = `usa-ce-${Math.random().toString(36).slice(2, 8)}`;
          this.insertAdjacentHTML(
            'beforeend',
            `<div class="usa-ce-bar" data-usa-part><div role="tablist" aria-label="Code format">${fm.map((f) => `<button type="button" role="tab" data-f="${f}" aria-controls="${id}">${LABELS[f]}</button>`).join('')}</div><button type="button" class="usa-ce-copy">Copy</button></div><pre class="usa-ce-code" id="${id}" role="tabpanel" tabindex="0" data-usa-part><code></code></pre>`
          );
          this.listen(this, 'click', (e: Event) => {
            const t = e.target as HTMLElement;
            const tab = t.closest?.('[data-f]') as HTMLElement | null;
            if (tab && this.contains(tab)) this.format = tab.dataset.f as ExportFormat;
            if (t.closest?.('.usa-ce-copy')) void this.copy();
          });
          this.listen(this, 'keydown', (e: KeyboardEvent) => {
            if (!(e.target as Element).closest?.('[role=tab]')) return;
            const l = this.fmts();
            const j = arrowIndex(e, l.indexOf(this._f), l.length); // 13.1.0: Home / End too
            if (j < 0) return;
            e.preventDefault();
            this.format = l[j];
            (this.querySelector(`[data-f="${this._f}"]`) as HTMLElement | null)?.focus();
          });
          const s = this.src();
          if (s && typeof MutationObserver !== 'undefined') {
            this._mo?.disconnect();
            this._mo = new MutationObserver(() => this.render());
            this._mo.observe(s, { attributes: true, attributeFilter: undefined });
            this.onCleanup(() => this._mo?.disconnect());
          }
          this.render();
        }
        private render(): void {
          this.querySelectorAll<HTMLElement>('[data-f]').forEach((b) => {
            const on = b.dataset.f === this._f;
            b.setAttribute('aria-selected', String(on));
            b.tabIndex = on ? 0 : -1;
          });
          const c = this.querySelector('.usa-ce-code code');
          if (c) c.textContent = this.code;
        }
        async copy(): Promise<boolean> {
          let ok = false;
          try {
            await navigator.clipboard.writeText(this.code);
            ok = true;
          } catch {
            ok = false;
          }
          const b = this.querySelector('.usa-ce-copy');
          if (b) {
            b.textContent = ok ? 'Copied ✓' : 'Select & copy';
            setTimeout(() => (b.textContent = 'Copy'), 1500);
          }
          if (ok && !this.reduced) this.motion(this.querySelector('.usa-ce-code') as Element, [{ boxShadow: '0 0 0 2px #22c55e' }, { boxShadow: '0 0 0 0 transparent' }], { duration: 600 });
          this.emit('copy', { format: this._f, ok });
          return ok;
        }
      }
      return UsaCodeExport as unknown as CustomElementConstructor;
    },
    { id: 'code-export', text: css }
  );
}
